#methodFeatureInclusion:
#  - MethodAssignStmtCount
wholeProgFeatureInclusion:
  - WholeProgramAPICallCount
featureResources:
#  - { featureName: "ClassContainsField", featureValue: "NOP" }
#  - { featureName: "ClassContainsMethod", featureValue: "toString" }
#  - { featureName: "ClassNameContains", featureValue: "Utils" }
#  - { featureName: "ClassNameEndsWith", featureValue: "Utils" }
#  - { featureName: "ClassPackageNameEquals", featureValue: "org.apache.commons.lang3.tuple"}
#
#  - { featureName: "MethodCallsMethod", featureValue: "{ArrayUtils, getLength}" }
#  - { featureName: "MethodCallClassContains", featureValue: "Comparator" }
#  - { featureName: "MethodCallContains", featureValue: "compare" }
#  - { featureName: "MethodCallFlowsToReturn", featureValue: "append"}
#  - { featureName: "MethodCallOnParameterContains", featureValue: "append" }
#  - { featureName: "MethodClassNameContains", featureValue: "ArrayUtils" }
#  - { featureName: "MethodClassNameEndsWith", featureValue: "Utils" }
#  - { featureName: "MethodClassNameEquals", featureValue: "StringUtils" }
#  - { featureName: "MethodClassPackageNameEquals", featureValue: "org.apache.commons.lang3.tuple"}
#  - { featureName: "MethodContainsObject", featureValue: "String" }
#  - { featureName: "MethodNameContains", featureValue: "Utils" }
#  - { featureName: "MethodNameEquals", featureValue: "append" }
#  - { featureName: "MethodNameNotContains", featureValue: "append" }
#  - { featureName: "MethodNameStartsWith", featureValue: "append" }
#  - { featureName: "MethodParamContainsTypeOrName", featureValue: "float"}
#  - { featureName: "MethodParamFlowsToMethod", featureValue: "indexesOf" }
#  - { featureName: "MethodReturnTypeContainsName", featureValue: "java.util.List"}
#  - { featureName: "MethodReturnTypeEquals", featureValue: "java.util.List"}
#
  - { featureName: "WholeProgramAPICallCount", featureValue: "/Users/ashikmr/Desktop/SootFX/src/main/resources/MethodSignatures.txt" }
#  - { featureName: "WholeProgramContainsAPICall", featureValue: "min" }